#!/usr/bin/env python3
"""Evaluate compact pose and leakage-safe residual integration in both directions.

The residual arm never trains on in-sample B5 residuals.  Each residual used to
fit the compact pose head is generated by a leave-one-out B5 fit within the
currently available prefix (or within the frozen source domain).  This keeps
the pose upgrade an error-correction layer rather than a second route for
label leakage.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from core import (
    GuardedEnsemble,
    build_feature_matrix,
    canonical_overlap,
    fit_ridge,
    load_reaction_rows,
    predict_ridge,
    remove_canonical_overlap,
)


def _matrix(rows, arm):
    matrix, names = build_feature_matrix(rows, arm)
    return matrix, list(names)


def _align(matrix: np.ndarray, names: list[str], wanted: list[str]) -> np.ndarray:
    if names == wanted:
        return matrix
    positions = {name: index for index, name in enumerate(names)}
    return np.column_stack([matrix[:, positions[name]] if name in positions else np.zeros(len(matrix)) for name in wanted])


def _loo_b5_residuals(X: np.ndarray, y: np.ndarray, alpha: float) -> np.ndarray:
    """Return cross-fitted residuals; no observation predicts itself."""

    if len(y) < 2:
        return np.zeros(len(y), dtype=float)
    values = np.zeros(len(y), dtype=float)
    for index in range(len(y)):
        keep = np.arange(len(y)) != index
        fitted = fit_ridge(X[keep], y[keep], alpha)
        values[index] = y[index] - float(predict_ridge(fitted, X[index:index + 1])[0])
    return values


def _fit_residual_head(X_pose: np.ndarray, X_b5: np.ndarray, y: np.ndarray, alpha: float):
    residuals = _loo_b5_residuals(X_b5, y, alpha)
    return fit_ridge(X_pose, residuals, alpha)


def _metrics(rows: list[dict], key: str) -> dict[str, float | int | None]:
    if not rows:
        return {"count": 0, "mae": None, "auc_mae": None}
    errors = np.asarray([abs(float(row[key]) - float(row["observed"])) for row in rows], dtype=float)
    prefixes = np.asarray([float(row["prefix_size"]) for row in rows], dtype=float)
    return {"count": int(len(errors)), "mae": float(np.mean(errors)), "auc_mae": float(np.trapezoid(errors, prefixes))}


def _replay(source, target, source_domain: str, target_name: str, *, alpha: float = 10.0) -> dict:
    source = [row for row in source if row.value(target_name) is not None]
    target = [row for row in target if row.value(target_name) is not None]
    source = remove_canonical_overlap(source, target)
    if len(source) < 2 or len(target) <= 2:
        raise ValueError("pose upgrade needs at least two source and three target observations")

    source_b5, b5_names = _matrix(source, "B5")
    source_p3, p3_names = _matrix(source, "P3")
    target_b5, target_b5_names = _matrix(target, "B5")
    target_p3, target_p3_names = _matrix(target, "P3")
    if b5_names != target_b5_names or p3_names != target_p3_names:
        raise ValueError("source and target feature names do not align")
    compact_start = len(b5_names)
    source_pose = source_p3[:, compact_start:]
    target_pose = target_p3[:, compact_start:]
    source_y = np.asarray([row.value(target_name) for row in source], dtype=float)
    ordered = sorted(target, key=lambda row: row.source_order)
    target_index = {row.substrate_id: index for index, row in enumerate(target)}
    source_b5_model = fit_ridge(source_b5, source_y, alpha)
    source_residual_model = _fit_residual_head(source_pose, source_b5, source_y, alpha)
    ensemble = GuardedEnsemble(names=("target_only", "source", "combined"), initial_weights=np.asarray([0.6, 0.2, 0.2]))
    output: list[dict] = []
    for prefix_size in range(2, len(ordered)):
        train = ordered[:prefix_size]
        test = ordered[prefix_size]
        indices = [target_index[row.substrate_id] for row in train]
        test_index = target_index[test.substrate_id]
        train_y = np.asarray([row.value(target_name) for row in train], dtype=float)
        target_b5_train = target_b5[indices]
        target_pose_train = target_pose[indices]
        target_b5_model = fit_ridge(target_b5_train, train_y, alpha)
        target_base = float(predict_ridge(target_b5_model, target_b5[test_index:test_index + 1])[0])
        target_residual_model = _fit_residual_head(target_pose_train, target_b5_train, train_y, alpha)
        target_correction = float(predict_ridge(target_residual_model, target_pose[test_index:test_index + 1])[0])
        target_residual = float(np.clip(target_base + target_correction, 0.0, 100.0))
        source_base = float(predict_ridge(source_b5_model, target_b5[test_index:test_index + 1])[0])
        source_correction = float(predict_ridge(source_residual_model, target_pose[test_index:test_index + 1])[0])
        source_residual = float(np.clip(source_base + source_correction, 0.0, 100.0))
        direct_p3_model = fit_ridge(np.vstack([source_p3, target_p3[indices]]), np.concatenate([source_y, train_y]), alpha)
        direct_p3 = float(predict_ridge(direct_p3_model, target_p3[test_index:test_index + 1])[0])
        pooled_b5 = fit_ridge(np.vstack([source_b5, target_b5_train]), np.concatenate([source_y, train_y]), alpha)
        pooled = float(predict_ridge(pooled_b5, target_b5[test_index:test_index + 1])[0])
        active_source = source_residual
        predictions = {"target_b5": target_base, "target_residual_pose": target_residual, "source_b5": source_base, "source_residual_pose": source_residual, "direct_p3_pooled": direct_p3, "pooled_b5": pooled}
        ensemble_values = {"target_only": target_residual, "source": active_source, "combined": pooled}
        guarded, weights = ensemble.combine(ensemble_values)
        observed = float(test.value(target_name))
        ensemble.update(ensemble_values, observed)
        output.append({"prefix_size": prefix_size, "test_substrate_id": test.substrate_id, "observed": observed, "predictions": predictions, **predictions, "guarded_residual_pose": guarded, "guarded_weights_before_update": weights})
    keys = ["target_b5", "target_residual_pose", "source_b5", "source_residual_pose", "direct_p3_pooled", "pooled_b5", "guarded_residual_pose"]
    return {"source_domain": source_domain, "source_count": len(source), "target_count": len(target), "rows": output, "metrics": {key: _metrics(output, key) for key in keys}}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--p7-records", type=Path, required=True)
    parser.add_argument("--cmcpor-records", type=Path, required=True)
    parser.add_argument("--p7-stage2p", type=Path, required=True)
    parser.add_argument("--cmcpor-stage2p", type=Path, required=True)
    parser.add_argument("--target", choices=("ee_percent", "isolated_yield_percent"), default="ee_percent")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    p7 = load_reaction_rows(args.p7_records, catalyst="fe-p7-cl", target=args.target, include_unlabelled=True, pose_features_path=args.p7_stage2p)
    cmc = load_reaction_rows(args.cmcpor_records, catalyst="cmcpor-fecl", target=args.target, include_unlabelled=True, pose_features_path=args.cmcpor_stage2p)
    cmc_aryl = [row for row in cmc if row.family_id == "angew-aryl-c-h-amination"]
    report = {"schema_version": "pptl-pose-upgrade-report-v1", "target": args.target, "pose_arm": "P3_compact_stage2p", "pose_feature_count": 44, "canonical_overlap_count": len(canonical_overlap(p7, cmc_aryl)), "directions": {"p7_to_cmcpor_aryl": _replay(p7, cmc_aryl, "fe-p7-cl", args.target), "cmcpor_to_p7_aryl": _replay(cmc_aryl, p7, "cmcpor-fecl", args.target)}}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({direction: value["metrics"] for direction, value in report["directions"].items()}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
